### ISSUE TITLE
gnome-icon-theme-symbolic requirement

### ISSUE THREAD

**Issue by jtojnar** [RaaH/gscrabble#3]
The readme lists `gnome-icon-theme-symbolic` under dependencies, but it is old and unmaintained. Could you clarify why this is needed?

**Comment by RaaH** [comment]
thanks

**Comment by jtojnar** [comment]
Thanks for fixing it in https://github.com/RaaH/gscrabble/commit/5a09e78709ea1c533b25961dc020f179b384b0a1.
